USE [sipr]
GO
select count(*) from  [dbo].[srs_acd_history]
select count(*) from  [dbo].[srs_acd_history_revised]

/****** Object:  Table [dbo].[srs_acd_history_revised]    Script Date: 7/4/2025 12:16:29 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[srs_acd_history]') AND type in (N'U'))
DROP TABLE [dbo].[srs_acd_history]
GO

/****** Object:  Table [dbo].[srs_acd_history_revised]    Script Date: 7/4/2025 12:16:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[srs_acd_history](
	[ETL_Date] [date] NULL,
	[ETL_Time] [nvarchar](8) NULL,
	[Student code] [nvarchar](12) NOT NULL,
	[APF sequence number] [nvarchar](2) NOT NULL,
	[Sequence number] [nvarchar](2) NOT NULL,
	[Sort name] [nvarchar](15) NULL,
	[Date created] [datetime] NULL,
	[Time created] [datetime] NULL,
	[Status code] [nvarchar](6) NULL,
	[Applicant Category code] [nvarchar](12) NULL,
	[Student Funding Category] [nvarchar](6) NULL,
	[Scheme code] [nvarchar](6) NULL,
	[MAS Course code] [nvarchar](15) NULL,
	[Academic Year code] [nvarchar](12) NULL,
	[Month of Entry code] [nvarchar](6) NULL,
	[Decision Statistics Cat] [nvarchar](12) NULL,
	[Recruitment state] [nvarchar](4) NULL,
	[Department code] [nvarchar](12) NULL,
	[Course code] [nvarchar](15) NULL,
	[Block] [nvarchar](4) NULL,
	[Occurrence] [nvarchar](6) NULL,
	[Programme of Study code] [nvarchar](12) NULL,
	[Route code] [nvarchar](12) NULL,
	[Mode of Attendance code] [nvarchar](6) NULL,
	[Student Course Join code] [nvarchar](15) NULL,
	[Reason for transfer code] [nvarchar](6) NULL,
	[Withdrawal date] [datetime] NULL,
	[Preference] [numeric](2, 0) NULL,
	[Released] [nvarchar](1) NULL,
	[Interview/open day invite] [nvarchar](1) NULL,
	[Latest Interview Date] [datetime] NULL,
	[Clearing] [nvarchar](1) NULL,
	[GTTR student id] [numeric](6, 0) NULL,
	[SWAS Student identifier] [numeric](6, 0) NULL,
	[Reference ID] [nvarchar](10) NULL,
	[UCAS choice] [nvarchar](4) NULL,
	[UCAS Course code] [nvarchar](15) NULL,
	[UCAS Campus code] [nvarchar](3) NULL,
	[UCAS Faculty code] [nvarchar](1) NULL,
	[Valid Dec and Resp] [nvarchar](8) NULL,
	[Stage] [nvarchar](1) NULL,
	[Qualification Status code] [nvarchar](3) NULL,
	[Initial Decision] [nvarchar](1) NULL,
	[Initial Response] [nvarchar](1) NULL,
	[Confirmation Decision] [nvarchar](1) NULL,
	[Confirmation Response] [nvarchar](1) NULL,
	[Clearing Decision] [nvarchar](1) NULL,
	[Clearing Response] [nvarchar](1) NULL,
	[Institution Dec/Rsp] [nvarchar](6) NULL,
	[Applicant Acceptance Stat] [nvarchar](3) NULL,
	[Acceptance Decision date] [datetime] NULL,
	[Acceptance Response date] [datetime] NULL,
	[Conditional offer date] [datetime] NULL,
	[Conditional Acceptance Date] [datetime] NULL,
	[Change Source] [nvarchar](1) NULL,
	[Change course] [nvarchar](1) NULL,
	[Change offer] [nvarchar](1) NULL,
	[Change year] [nvarchar](1) NULL,
	[Change month] [nvarchar](1) NULL,
	[Change attendance mode] [nvarchar](1) NULL,
	[Change point of entry] [nvarchar](1) NULL,
	[UCAS notified decision] [nvarchar](3) NULL,
	[UCAS notified response] [nvarchar](3) NULL,
	[UCAS transaction type] [nvarchar](2) NULL,
	[Admissions Entry System] [nvarchar](1) NULL,
	[Batch] [nvarchar](12) NULL,
	[UCAS send decn/outcome] [nvarchar](3) NULL,
	[Send offer] [nvarchar](1) NULL,
	[UCAS Error Numbers code] [nvarchar](12) NULL,
	[UCAS Confirmation Status] [nvarchar](4) NULL,
	[UCAS Confirmation History] [nvarchar](4) NULL,
	[UCAS Substitution code] [nvarchar](4) NULL,
	[Live at home] [nvarchar](1) NULL,
	[Offer Library code] [nvarchar](12) NULL,
	[Secondary offer code] [nvarchar](12) NULL,
	[Exemptions Profile code] [nvarchar](12) NULL,
	[Exemption awarded date] [datetime] NULL,
	[Non-academic condition me] [nvarchar](3) NULL,
	[GTTR maths achievement] [nvarchar](1) NULL,
	[GTTR english achievement] [nvarchar](1) NULL,
	[GTTR Science Flag] [nvarchar](1) NULL,
	[Admissions route] [nvarchar](1) NULL,
	[Residence required] [nvarchar](1) NULL,
	[Tutor code] [nvarchar](12) NULL,
	[Other tutor code] [nvarchar](12) NULL,
	[Faculty code] [nvarchar](6) NULL,
	[Course length] [numeric](3, 0) NULL,
	[Expected End Date] [datetime] NULL,
	[Start date] [datetime] NULL,
	[GTTR modular?] [nvarchar](1) NULL,
	[External Reference] [nvarchar](20) NULL,
	[MCR UCAS GUID] [nvarchar](3) NULL,
	[CRS UCAS GUID] [nvarchar](15) NULL,
	[Inst Academic Clearance] [nvarchar](15) NULL,
	[Inst Financial Clearance] [nvarchar](15) NULL,
	[User Defined Field 01] [nvarchar](15) NULL,
	[User Defined Field 02] [nvarchar](15) NULL,
	[User Defined Field 03] [nvarchar](15) NULL,
	[User Defined Field 04] [nvarchar](15) NULL,
	[User Defined Field 05] [nvarchar](15) NULL,
	[User Defined Field 06] [nvarchar](15) NULL,
	[User Defined Field 07] [nvarchar](15) NULL,
	[User Defined Field 08] [nvarchar](15) NULL,
	[User Defined Field 09] [nvarchar](15) NULL,
	[User Defined Field 10] [nvarchar](15) NULL,
	[User Defined Field 11] [nvarchar](15) NULL,
	[User Defined Field 12] [nvarchar](15) NULL,
	[User Defined Field 13] [nvarchar](15) NULL,
	[User Defined Field 14] [nvarchar](15) NULL,
	[User Defined Field 15] [nvarchar](15) NULL,
	[User Defined Field 16] [nvarchar](100) NULL,
	[User Defined Field 17] [nvarchar](100) NULL,
	[User Defined Field 18] [nvarchar](100) NULL,
	[User Defined Field 19] [nvarchar](100) NULL,
	[User Defined Field 20] [nvarchar](100) NULL,
	[Fee Amount] [nvarchar](250) NULL,
	[Reply to offer by date] [datetime] NULL,
	[Registration date] [datetime] NULL,
	[Detail from Section 3F] [nvarchar](32) NULL,
	[Extra round no] [nvarchar](6) NULL,
	[Application Location] [nvarchar](10) NULL,
	[Extra application status] [nvarchar](12) NULL,
	[Institutions code] [nvarchar](12) NULL,
	[Schools Direct code] [nvarchar](12) NULL,
	[Alternate UCAS id] [nvarchar](12) NULL,
	[Principal study area/inst] [nvarchar](12) NULL,
	[Secondary study area/inst] [nvarchar](12) NULL,
	[Decision date2] [datetime] NULL,
	[Decision time2] [datetime] NULL,
	[Response date2] [datetime] NULL,
	[Response time2] [datetime] NULL,
	[Age On Entry] [numeric](4, 0) NULL,
	[Interview Time] [datetime] NULL,
	[Study Mode] [nvarchar](12) NULL,
	[Audition Method] [nvarchar](4) NULL,
	[Reject by default date] [datetime] NULL,
	[Audition Date & Time 1] [datetime] NULL,
	[Audition Date & Time 2] [nvarchar](12) NULL,
	[Cycle of application] [nvarchar](7) NULL,
	[Temp. Reference] [nvarchar](12) NULL,
	[Application id] [nvarchar](15) NULL,
	[Referred Date] [nvarchar](12) NULL,
	[IPR booking reference] [nvarchar](12) NULL,
	[IPP user code] [nvarchar](12) NULL,
	[IPP code] [nvarchar](12) NULL,
	[IPO sequence number] [nvarchar](12) NULL,
	[IPR sequence number] [nvarchar](12) NULL,
	[Adjustment] [nvarchar](12) NULL,
	[Self-certified for GTCE] [nvarchar](12) NULL,
	[ELQ status] [nvarchar](15) NULL,
	[Interview response] [nvarchar](15) NULL,
	[Course Group code] [nvarchar](6) NULL,
	[Criminal Record?] [nvarchar](6) NULL,
	[Total SQE points] [nvarchar](6) NULL,
	[DMU action] [nvarchar](7) NULL,
	[Overseas Hlth Cvr Dur] [nvarchar](12) NULL,
	[Overseas Hlth Cover Type] [nvarchar](12) NULL,
	[Fee status code1] [nvarchar](12) NULL,
	[Fee status code2] [nvarchar](12) NULL,
	[AAB+ Status] [nvarchar](12) NULL,
	[UCAS Programme code] [nvarchar](12) NULL,
	[Respond by Date1] [datetime] NULL,
	[Respond by Date2] [datetime] NULL,
	[Respond by Date3] [datetime] NULL,
	[Paperless stage code1] [nvarchar](4) NULL,
	[Paperless stage code2] [nvarchar](4) NULL,
	[Paperless stage code3] [nvarchar](4) NULL,
	[Paperless stage code4] [nvarchar](4) NULL,
	[Paperless stage code5] [nvarchar](4) NULL,
	[Mature applicant?] [nvarchar](100) NULL,
	[CAS Required] [nvarchar](100) NULL,
	[CUKAS fee collected] [nvarchar](1) NULL,
	[CUKAS fee code] [nvarchar](1) NULL,
	[Souce of interest] [nvarchar](6) NULL,
	[Previously applied] [nvarchar](12) NULL,
	[Main subject] [nvarchar](50) NULL,
	[Second subject] [nvarchar](1) NULL,
	[Deferred Entry] [nvarchar](2) NULL,
	[Joint type] [numeric](3, 0) NULL,
	[Substituted Date] [datetime] NULL,
	[How Heard About Course] [nvarchar](36) NULL,
	[Is Second or Joint Area] [nvarchar](36) NULL,
	[Fee Code] [nvarchar](36) NULL,
	[Rank] [numeric](3, 0) NULL,
	[Package flag] [nvarchar](12) NULL,
	[Current Folder] [nvarchar](36) NULL,
	[Location code] [nvarchar](12) NULL,
	[VDR UCAS Trans code] [nvarchar](12) NULL,
	[ECI Code] [nvarchar](12) NULL,
	[Assigned to code] [nvarchar](6) NULL,
	[Basis of Admissions code] [nvarchar](6) NULL,
	[Action from service form] [nvarchar](1) NULL,
	[Partner Institution code] [nvarchar](1) NULL,
	[Overseas Institution code] [nvarchar](1) NULL,
	[Stage One Offer Letter] [nvarchar](6) NULL,
	[Stage Two Offer Letter] [nvarchar](1) NULL,
	[Stage Three Offer Letter] [nvarchar](1) NULL,
	[Self Released Report Note] [nvarchar](1) NULL,
	[Currency code] [nvarchar](1) NULL,
	[Highest Eligible] [nvarchar](1) NULL,
	[Notes] [nvarchar](1) NULL,
	[Offer Notes] [nvarchar](1) NULL,
	[Offer Text] [nvarchar](1) NULL
) ON [PRIMARY]
GO

INSERT INTO [dbo].[srs_acd_history]
SELECT * FROM [dbo].[srs_acd_history_REVISED];

select count(*) from  [dbo].[srs_acd_history]
select count(*) from  [dbo].[srs_acd_history_revised]

