USE [sipr]

select count(*) from [dbo].[srs_acd_history];
select count(*) from [dbo].[srs_acd_history_revised];
USE [sipr]
GO
truncate table [dbo].[srs_acd_history_revised];
INSERT INTO [dbo].[srs_acd_history_revised]
           ([ETL_Date]
           ,[ETL_Time]
           ,[Student code]
           ,[APF sequence number]
           ,[Sequence number]
           ,[Sort name]
           ,[Date created]
           ,[Time created]
           ,[Status code]
           ,[Applicant Category code]
           ,[Student Funding Category]
           ,[Scheme code]
           ,[MAS Course code]
           ,[Academic Year code]
           ,[Month of Entry code]
           ,[Decision Statistics Cat]
           ,[Recruitment state]
           ,[Department code]
           ,[Course code]
           ,[Block]
           ,[Occurrence]
           ,[Programme of Study code]
           ,[Route code]
           ,[Mode of Attendance code]
           ,[Student Course Join code]
           ,[Reason for transfer code]
           ,[Withdrawal date]
           ,[Preference]
           ,[Released]
           ,[Interview/open day invite]
           ,[Latest Interview Date]
         ,[Clearing]
           ,[GTTR student id]
           ,[SWAS Student identifier]
           ,[Reference ID]
           ,[UCAS choice]
           ,[UCAS Course code]
           ,[UCAS Campus code]
           ,[UCAS Faculty code]
           ,[Valid Dec and Resp]
           ,[Stage]
           ,[Qualification Status code]
           ,[Initial Decision]
           ,[Initial Response]
           ,[Confirmation Decision]
           ,[Confirmation Response]
           ,[Clearing Decision]
           ,[Clearing Response]
           ,[Institution Dec/Rsp]
           ,[Applicant Acceptance Stat]
           ,[Acceptance Decision date]
           ,[Acceptance Response date]
           ,[Conditional offer date]
           ,[Conditional Acceptance Date]
             ,[Change Source]
           ,[Change course]
           ,[Change offer]
           ,[Change year]
           ,[Change month]
           ,[Change attendance mode]
           ,[Change point of entry]
           ,[UCAS notified decision]
           ,[UCAS notified response]
           ,[UCAS transaction type]
           ,[Admissions Entry System]
           ,[Batch]
           ,[UCAS send decn/outcome]
           ,[Send offer]
           ,[UCAS Error Numbers code]
           ,[UCAS Confirmation Status]
           ,[UCAS Confirmation History]
           ,[UCAS Substitution code]
           ,[Live at home]
           ,[Offer Library code]
           ,[Secondary offer code]
           ,[Exemptions Profile code]
           ,[Exemption awarded date]
           ,[Non-academic condition me]
           ,[GTTR maths achievement]
           ,[GTTR english achievement]
           ,[GTTR Science Flag]
           ,[Admissions route]
           ,[Residence required]
           ,[Tutor code]
           ,[Other tutor code]
           ,[Faculty code]
           ,[Course length]
           ,[Expected End Date]
           ,[Start date]
           ,[GTTR modular?]
           ,[External Reference]
           ,[MCR UCAS GUID]
           ,[CRS UCAS GUID]
           ,[Inst Academic Clearance]
           ,[Inst Financial Clearance]
           ,[User Defined Field 01]
           ,[User Defined Field 02]
           ,[User Defined Field 03]
           ,[User Defined Field 04]
           ,[User Defined Field 05]
           ,[User Defined Field 06]
           ,[User Defined Field 07]
           ,[User Defined Field 08]
           ,[User Defined Field 09]
           ,[User Defined Field 10]
           ,[User Defined Field 11]
           ,[User Defined Field 12]
           ,[User Defined Field 13]
           ,[User Defined Field 14]
           ,[User Defined Field 15]
           ,[User Defined Field 16]
           ,[User Defined Field 17]
           ,[User Defined Field 18]
           ,[User Defined Field 19]
           ,[User Defined Field 20]
           ,[Fee Amount]
           ,[Reply to offer by date]
           ,[Registration date]
           ,[Detail from Section 3F]
           ,[Extra round no]
           ,[Application Location]
           ,[Extra application status]
           ,[Institutions code]
           ,[Schools Direct code]
           ,[Alternate UCAS id]
           ,[Principal study area/inst]
           ,[Secondary study area/inst]
           ,[Decision date2]
           ,[Decision time2]
           ,[Response date2]
           ,[Response time2]
           ,[Age On Entry]
           ,[Interview Time]
           ,[Study Mode]
           ,[Audition Method]
           ,[Reject by default date]
           ,[Audition Date & Time 1]
           ,[Audition Date & Time 2]
           ,[Cycle of application]
           ,[Temp. Reference]
           ,[Application id]
           ,[Referred Date]
           ,[IPR booking reference]
           ,[IPP user code]
           ,[IPP code]
           ,[IPO sequence number]
           ,[IPR sequence number]
           ,[Adjustment]
           ,[Self-certified for GTCE]
           ,[ELQ status]
           ,[Interview response]
           ,[Course Group code]
           ,[Criminal Record?]
           ,[Total SQE points]
           ,[DMU action]
           ,[Overseas Hlth Cvr Dur]
           ,[Overseas Hlth Cover Type]
           ,[Fee status code1]
           ,[Fee status code2]
           ,[AAB+ Status]
           ,[UCAS Programme code]
           ,[Respond by Date1]
           ,[Respond by Date2]
           ,[Respond by Date3]
           ,[Paperless stage code1]
           ,[Paperless stage code2]
           ,[Paperless stage code3]
           ,[Paperless stage code4]
           ,[Paperless stage code5]
           ,[Mature applicant?]
           ,[CAS Required]
           ,[CUKAS fee collected]
           ,[CUKAS fee code]
           ,[Souce of interest]
           ,[Previously applied]
           ,[Main subject]
           ,[Second subject]
           ,[Deferred Entry]
           ,[Joint type]
           ,[Substituted Date]
           ,[How Heard About Course]
           ,[Is Second or Joint Area]
           ,[Fee Code]
           ,[Rank]
           ,[Package flag]
           ,[Current Folder]
           ,[Location code]
           ,[VDR UCAS Trans code]
           ,[ECI Code]
           ,[Assigned to code]
           ,[Basis of Admissions code]
           ,[Action from service form]
           ,[Partner Institution code]
           ,[Overseas Institution code]
           ,[Stage One Offer Letter]
           ,[Stage Two Offer Letter]
           ,[Stage Three Offer Letter]
           ,[Self Released Report Note]
           ,[Currency code]
           ,[Highest Eligible]
           ,[Notes]
           ,[Offer Notes]
           ,[Offer Text])
SELECT [ETL_Date]
      ,[ETL_Time]
      ,[Student code]
      ,[APF sequence number]
      ,[Sequence number]
      ,[Sort name]
      ,try_cast([Date created]as datetime)
      ,try_cast([Time created]as datetime)
     ,[Status code]
      ,[Applicant Category code]
      ,[Student Funding Category]
      ,[Scheme code]
      ,[MAS Course code]
      ,[Academic Year code]
      ,[Month of Entry code]
      ,[Decision Statistics Cat]
      ,[Recruitment state]
      ,[Department code]
      ,[Course code]
      ,[Block]
      ,[Occurrence]
      ,[Programme of Study code]
      ,[Route code]
      ,[Mode of Attendance code]
      ,[Student Course Join code]
      ,[Reason for transfer code]
      ,try_cast([Withdrawal date]as datetime)
      ,[Preference]
      ,[Released]
      ,[Interview/open day invite]
      ,try_cast([Latest Interview Date]as datetime)
      ,[Clearing]
      ,[GTTR student id]
      ,[SWAS Student identifier]
      ,[Reference ID]
      ,[UCAS choice]
      ,[UCAS Course code]
      ,[UCAS Campus code]
      ,[UCAS Faculty code]
      ,[Valid Dec and Resp]
      ,[Stage]
      ,[Qualification Status code]
      ,[Initial Decision]
      ,[Initial Response]
      ,[Confirmation Decision]
      ,[Confirmation Response]
      ,[Clearing Decision]
      ,[Clearing Response]
      ,[Institution Dec/Rsp]
      ,[Applicant Acceptance Stat]
      ,try_cast([Acceptance Decision date]as datetime)
      ,try_cast([Acceptance Response date]as datetime)
      ,try_cast([Conditional offer date]as datetime)
      ,try_cast([Conditional Acceptance Date]as datetime)
       ,[Change Source]
      ,[Change course]
      ,[Change offer]
      ,[Change year]
      ,[Change month]
      ,[Change attendance mode]
      ,[Change point of entry]
      ,[UCAS notified decision]
      ,[UCAS notified response]
      ,[UCAS transaction type]
      ,[Admissions Entry System]
      ,[Batch]
      ,[UCAS send decn/outcome]
      ,[Send offer]
      ,[UCAS Error Numbers code]
      ,[UCAS Confirmation Status]
      ,[UCAS Confirmation History]
      ,[UCAS Substitution code]
      ,[Live at home]
      ,[Offer Library code]
      ,[Secondary offer code]
      ,[Exemptions Profile code]
      ,try_cast([Exemption awarded date]as datetime)
      ,[Non-academic condition me]
      ,[GTTR maths achievement]
      ,[GTTR english achievement]
      ,[GTTR Science Flag]
      ,[Admissions route]
      ,[Residence required]
      ,[Tutor code]
      ,[Other tutor code]
      ,[Faculty code]
      ,[Course length]
      ,try_cast([Expected End Date]as datetime)
      ,try_cast([Start date]as datetime)
      ,[GTTR modular?]
      ,[External Reference]
      ,[MCR UCAS GUID]
      ,[CRS UCAS GUID]
      ,[Inst Academic Clearance]
      ,[Inst Financial Clearance]
      ,[User Defined Field 01]
      ,[User Defined Field 02]
      ,[User Defined Field 03]
      ,[User Defined Field 04]
      ,[User Defined Field 05]
      ,[User Defined Field 06]
      ,[User Defined Field 07]
      ,[User Defined Field 08]
      ,[User Defined Field 09]
      ,[User Defined Field 10]
      ,[User Defined Field 11]
      ,[User Defined Field 12]
      ,[User Defined Field 13]
      ,[User Defined Field 14]
      ,[User Defined Field 15]
      ,[User Defined Field 16]
      ,[User Defined Field 17]
      ,[User Defined Field 18]
      ,[User Defined Field 19]
      ,[User Defined Field 20]
      ,[Fee Amount]
      ,try_cast([Reply to offer by date]as datetime)
      ,try_cast([Registration date]as datetime)
      ,[Detail from Section 3F]
      ,[Extra round no]
      ,[Application Location]
      ,[Extra application status]
      ,[Institutions code]
      ,[Schools Direct code]
      ,[Alternate UCAS id]
      ,[Principal study area/inst]
      ,[Secondary study area/inst]
      ,try_cast([Decision date2]as datetime)
      ,try_cast([Decision time2]as datetime)
      ,try_cast([Response date2]as datetime)
      ,try_cast([Response time2]as datetime)
      ,convert(numeric(3,0),[Age On Entry])
      ,try_cast([Interview Time]as datetime)
      ,[Study Mode]
      ,[Audition Method]
      ,try_cast([Reject by default date]as datetime)
      ,try_cast([Audition Date & Time 1]as datetime)
      ,try_cast([Audition Date & Time 2]as datetime)
      ,[Cycle of application]
      ,[Temp. Reference]
      ,[Application id]
      ,try_cast([Referred Date]as datetime)
      ,[IPR booking reference]
      ,[IPP user code]
      ,[IPP code]
      ,[IPO sequence number]
      ,[IPR sequence number]
      ,[Adjustment]
      ,[Self-certified for GTCE]
      ,[ELQ status]
      ,[Interview response]
      ,[Course Group code]
      ,[Criminal Record?]
      ,[Total SQE points]
      ,[DMU action]
      ,[Overseas Hlth Cvr Dur]
      ,[Overseas Hlth Cover Type]
      ,[Fee status code1]
      ,[Fee status code2]
      ,[AAB+ Status]
      ,[UCAS Programme code]
      ,try_cast([Respond by Date1]as datetime)
      ,try_cast([Respond by Date2]as datetime)
      ,try_cast([Respond by Date3]as datetime)
      ,[Paperless stage code1]
      ,[Paperless stage code2]
      ,[Paperless stage code3]
      ,[Paperless stage code4]
      ,[Paperless stage code5]
      ,[Mature applicant?]
      ,[CAS Required]
      ,[CUKAS fee collected]
      ,[CUKAS fee code]
      ,[Souce of interest]
      ,[Previously applied]
      ,[Main subject]
      ,[Second subject]
      ,[Deferred Entry]
      ,[Joint type]
      ,try_cast([Substituted Date] as datetime)
      ,[How Heard About Course]
      ,[Is Second or Joint Area]
      ,[Fee Code]
     ,try_cast([Rank] as numeric(3,0))
      ,[Package flag]
      ,[Current Folder]
      ,[Location code]
      ,[VDR UCAS Trans code]
      ,[ECI Code]
      ,[Assigned to code]
      ,[Basis of Admissions code]
      ,[Action from service form]
      ,[Partner Institution code]
      ,[Overseas Institution code]
      ,[Stage One Offer Letter]
      ,[Stage Two Offer Letter]
      ,[Stage Three Offer Letter]
      ,[Self Released Report Note]
      ,[Currency code]
      ,[Highest Eligible]
      ,[Notes]
      ,[Offer Notes]
      ,[Offer Text]
  FROM [dbo].[srs_acd_history]

GO


